repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  has_issues: true
  has_wiki: false
  has_downloads: true

  default_branch: master
  delete_branch_on_merge: true

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

collaborators:
  - username: trevtrichbot
    permission: push
